apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    company: Evolvere
    component: nginx
  type: LoadBalancer
