apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - NoSql/
  - Sql/
  - db-config.yaml

namePrefix: database-

images:
  - name: mongo
    newTag: "4.4-rc"
  - name: postgres
    newTag: "14"
