apiVersion: v1
kind: Pod
metadata:
  name: python
spec:
  containers:
  - name: python
    image: python:3.8
    args:
    - sleep
    - "360"
    resources:
      requests:
        cpu: "10m"
      limits:
        cpu: "20m"
