swagger: "2.0"
info:
  title: DRW Demo
  version: "1.0.0"
consumes:
  - application/json
produces:
  - application/json

basePath: /api/v1

paths:
  /date-time:
    get:
      operationId: "backend.date_time"
      responses:
        "200":
          description: Returns server datetime.
