apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    args:
    - sleep
    - "360"
    env:
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: pod-password
            key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: pod-password
type: Opaque
data:
  password: "bXlob3ZlcmNyYWZ0aXNmdWxsb2ZlZWxzCg=="
