apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox:1.28
      args:
        - sleep
        - "360"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
    - name: busybox2
      image: busybox:1.28
      args:
        - sleep
        - "360"
      volumeMounts:
        - name: config-volume
          mountPath: /data
  volumes:
    - name: config-volume
      configMap:
        name: pod-vars
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-vars
data:
  vars: |
    log_level=debug
    environment=dev
  conf: |
    host=web.evolvere.link
